spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true
  http:
    clients:
      connect-timeout: 2s
      read-timeout: 10s

server:
  port: 8000
  shutdown: graceful

loresentry:
  upstream:
    graph-rag:
      base-url: http://graph-rag-api
    ai-chat:
      base-url: http://ai-chat-api
    authentication:
      base-url: http://authentication-api
    content:
      base-url: http://content-api
